workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    instance_size: xcode-large
    environment:
      flutter: latest
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
