workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa 
